const { ByteArray } = require("../ByteArray")

/**
 * Executes the given `.byte` command and returns the intermediate byte array
 * representation generated by the command.
 * @param {Command} command The command to execute.
 * @return {ByteArray} The byte array generated by the command.
 */
function byte (command) {
  const { line, params } = command
  if (params.length === 0) {
    return null
  }

  const bytes = []

  params.forEach(param => {
    if (param.isNumber()) {
      let value = param.data.value
      while (value > 0xff) {
        bytes.push(value & 0xff)
        value = value >>> 8
      }
      bytes.push(value)
    }
  })

  return new ByteArray({ bytes, line })
}

module.exports = { byte }
